Example/BloctoSDK/Info.plist, Example/BloctoSDK/ViewController.swift, Example/Tests/Info.plist
=> Feature dismiss keyboard after clicking done button.

Sources/Wallet/ParsedMethod.swift
=> Fix EVMBaseTransaction value parse

Example/BloctoSDK/Models/EVMBase.swift, Example/Podfile.lock
=> Fix change matic RPC url.

.github/workflows/ios.yml, Example/BloctoSDK.xcodeproj/project.pbxproj, Example/BloctoSDK/ViewControllers/FlowDemoViewController.swift, Example/Podfile.lock
=> Fix using api request to retrieve fee payer.

Example/BloctoSDK/ViewControllers/EVMBaseDemoViewController.swift, Example/BloctoSDK/ViewControllers/SolanaDemoViewController.swift, Sources/Core/BloctoSDK.swift, Sources/Core/Models/Error.swift
=> Feature add error type.

.circleci/config.yml, BloctoSDK.podspec, Example/BloctoSDK.xcodeproj/project.pbxproj, Example/BloctoSDK/Info.plist, Example/BloctoSDK/Utilities/ErrorHandler.swift, Example/BloctoSDK/ViewControllers/EVMBaseDemoViewController.swift, Example/BloctoSDK/ViewControllers/FlowDemoViewController.swift, Example/BloctoSDK/ViewControllers/SolanaDemoViewController.swift, Example/Podfile.lock, Example/Tests/Info.plist, Sources/Core/BloctoSDK.swift, Sources/Core/Models/Error.swift, Sources/Flow/BloctoFlowSDK.swift, Sources/Flow/Extensions/URLSessionExtension.swift, Sources/Solana/BloctoSolanaSDK.swift, Sources/Solana/SDKInfo.swift
=> Release 0.3.2

BloctoSDK.podspec, Sources/Solana/SDKInfo.swift, scripts/bump-version.sh
=> chore: bump version.

README.md, scripts/bump-version.sh
=> Docs update docs and script.

Example/BloctoSDK/ViewControllers/FlowDemoViewController.swift, Example/Podfile.lock
=> feat(demo): use toSwiftValue of flow-swift-sdk

Example/Podfile.lock, Sources/Flow/BloctoFlowSDK.swift
There should be no use case of getting fee payer other than current network.
=> Fix remove get fee payer isTestnet injection.

Sources/Core/BloctoSDK.swift
=> Fix only call main thread async if not in main thread.

Example/BloctoSDK.xcodeproj/project.pbxproj, Example/BloctoSDK/AppDelegate.swift, Example/BloctoSDK/Info.plist, Example/BloctoSDK/Models/EVMBase.swift, Example/BloctoSDK/ViewControllers/EVMBaseDemoViewController.swift, Example/BloctoSDK/ViewControllers/SolanaDemoViewController.swift, Example/Podfile, Example/Podfile.lock, Example/Tests/Methods/AccountRequestTests.swift, Example/Tests/Methods/SendTransactionTests.swift, Example/Tests/Methods/SignAndSendTransactionTests.swift, README.md, Sources/Core/BloctoEnvironment.swift, Sources/Core/BloctoSDK.swift, Sources/Solana/BloctoSolanaSDK.swift
as title. We also need to update the docs.
=> feat: change to dev environment

BloctoSDK.podspec, Example/BloctoSDK.xcworkspace/contents.xcworkspacedata, Example/Podfile.lock, README.md, Sources/Solana/SDKInfo.swift
=> Bump version 0.4.0

Example/Tests/QueryItemCoding/QueryItemEncodingTests.swift, Example/Tests/URLEncode/EVMBaseMethodURLEncodeTests.swift, Example/Tests/URLEncode/SolanaMethodURLEncodeTests.swift, Example/Tests/Utilities/XCTAssertURLEqual.swift, Sources/Core/Utilities/URLEncoding.swift
=> Fix url encoding.

Example/BloctoSDK/ViewControllers/SolanaDemoViewController.swift, Example/Tests/Methods/URLSessionMock.swift, Example/Tests/QueryItemCoding/QueryItemEncodingTests.swift, Sources/Core/Utilities/QueryDecoding.swift, Sources/Core/Utilities/URLEncoding.swift, Sources/Flow/Extensions/URLSessionExtension.swift, Sources/Solana/BloctoSolanaSDK.swift
=> Fix solana partial sign

.github/workflows/ios.yml
=> Chore github actions upgrade Xcode version.

Sources/Solana/BloctoSolanaSDK.swift
only convert tx needs partial sign.
=> Fix: solana tx convert.

LICENSE
=> chore: adjust license.

Example/Tests/Methods/SendTransactionTests.swift, Example/Tests/URLEncode/EVMBaseMethodURLEncodeTests.swift, Example/Tests/URLEncode/FlowMethodURLEncodeTests.swift, Example/Tests/URLEncode/SolanaMethodURLEncodeTests.swift, Sources/Core/Methods/RequestAccountMethod.swift, Sources/Core/Models/QueryName.swift, Sources/Core/Utilities/URLEncoding.swift, Sources/EVMBase/Methods/SendEVMBasedTransactionMethod.swift, Sources/EVMBase/Methods/SignEVMBaseMessageMethod.swift, Sources/Flow/Methods/AuthenticateMethod.swift, Sources/Flow/Methods/SendFlowTransactionMethod.swift, Sources/Flow/Methods/SignFlowMessageMethod.swift, Sources/Solana/Methods/SignAndSendSolanaTransactionMethod.swift
=> add: platform parameter

BloctoSDK.podspec
=> Fix rename a file.

Example/BloctoSDK/Models/EVMBase.swift, Example/BloctoSDK/ViewControllers/EVMBaseDemoViewController.swift
=> Fix replace bad polygon RPC.

scripts/bump-publish-version.sh
=> Chore update script

Sources/EVMBase/Methods/SendEVMBasedTransactionMethod.swift
we should use hex string to WebSDK fallback
=> Fix: EVM hex value.

Example/BloctoSDK/ViewControllers/EVMBaseDemoViewController.swift, Example/Podfile.lock
Signature Verification Migration of personalSign
=> Signature Verification Migration of personalSign

Example/BloctoSDK/Info.plist, Example/BloctoSDK/ViewControllers/EVMBaseDemoViewController.swift, Example/Tests/Info.plist
Signature Verification Migration of typedSign
=> Signature Verification Migration of typedSign

BloctoSDK.podspec, Example/Podfile.lock
=>  Update FlowSDK

BloctoSDK.podspec, Example/Gemfile.lock, Example/Podfile.lock
=> Chore - update FlowSDK
